#!/bin/sh

#~/Ghc/reg2/inplace/bin/ghc-stage2 -fllvm -optlc-O3 -optlo-simplifycfg -optlo-domtree -optlo-domfrontier -optlo-mem2reg -optlo-instcombine -optlo-globalopt -optlo-ipsccp -optlo-deadargelim -optlo-instcombine -optlo-simplifycfg -optlo-basiccg -optlo-prune-eh -optlo-inline -optlo-functionattrs -optlo-domtree -optlo-domfrontier -optlo-scalarrepl -optlo-simplify-libcalls -optlo-instcombine -optlo-lazy-value-info -optlo-jump-threading -optlo-simplifycfg -optlo-instcombine -optlo-tailcallelim -optlo-simplifycfg -optlo-reassociate -optlo-domtree -optlo-loops -optlo-loopsimplify -optlo-lcssa -optlo-loop-rotate -optlo-licm -optlo-lcssa -optlo-loop-unswitch -optlo-instcombine -optlo-scalar-evolution -optlo-loopsimplify -optlo-lcssa -optlo-iv-users -optlo-indvars -optlo-loop-deletion -optlo-instcombine -optlo-memdep -optlo-memcpyopt -optlo-sccp -optlo-instcombine -optlo-lazy-value-info -optlo-jump-threading -optlo-correlated-propagation -optlo-domtree -optlo-memdep -optlo-dse -optlo-adce -optlo-simplifycfg -optlo-strip-dead-prototypes -optlo-print-used-types -optlo-deadtypeelim -optlo-preverify -optlo-domtree -optlo-verify -fforce-recomp 4223.hs -o 4223-l -O2

~/Ghc/reg2/inplace/bin/ghc-stage2 -fllvm -optlc-O3 -optlo-simplifycfg -optlo-domtree -optlo-domfrontier -optlo-mem2reg -optlo-instcombine -optlo-globalopt -optlo-ipsccp -optlo-deadargelim -optlo-instcombine -optlo-simplifycfg -optlo-basiccg -optlo-prune-eh -optlo-inline -optlo-functionattrs -optlo-domtree -optlo-domfrontier -optlo-scalarrepl -optlo-simplify-libcalls -optlo-instcombine -optlo-lazy-value-info -optlo-jump-threading -optlo-simplifycfg -optlo-instcombine -fforce-recomp 4223.hs -o 4223-l -O2

# -optlo-tailcallelim -optlo-simplifycfg 
# -optlo-reassociate -optlo-domtree -optlo-loops -optlo-loopsimplify -optlo-lcssa -optlo-loop-rotate -optlo-licm -optlo-lcssa -optlo-loop-unswitch -optlo-instcombine -optlo-scalar-evolution -optlo-loopsimplify -optlo-lcssa -optlo-iv-users -optlo-indvars -optlo-loop-deletion -optlo-instcombine -optlo-memdep -optlo-memcpyopt -optlo-sccp -optlo-instcombine -optlo-lazy-value-info -optlo-jump-threading -optlo-correlated-propagation -optlo-domtree -optlo-memdep -optlo-dse -optlo-adce -optlo-simplifycfg -optlo-strip-dead-prototypes -optlo-print-used-types -optlo-deadtypeelim -optlo-preverify -optlo-domtree -optlo-verify 

